/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AHCISystem;

import static AHCISystem.dashboard.time;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Reycham
 */
public class userSignUp extends javax.swing.JFrame {
    Date d;
    SimpleDateFormat dd;

    /**
     * Creates new form userSignUp
     */
    public Connection conn;
    public Statement st;
    String sql;
    String r;
    public userSignUp() {
        initComponents();
        showDate();
    }
      public void add_data(){
            // TODO add your handling code here:
        try{
       //   Class.forName("com.mysql.jdbc.Driver");
        //  conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthcenter","root","");
          PreparedStatement ps = conn.prepareStatement("insert into staff_info(staff_id, f_name, m_name, l_name, birth_date, age, gender, status, position, phone, address, date_started, image)values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
          InputStream is = new FileInputStream(new File(r));
          ps.setString(1, idtf.getText());
          ps.setString(2, fnametf.getText());
          ps.setString(3,mnametf.getText());
          ps.setString(4,lnametf.getText());
          ps.setString(5,bdatetf.getText());
          ps.setString(6,agetf.getText());
          ps.setString(7,gender.getSelectedItem().toString());
          ps.setString(8,status.getSelectedItem().toString());
          ps.setString(9, position.getSelectedItem().toString());
          ps.setString(10,mobiletf.getText());
          ps.setString(11,addresstf.getText());
          ps.setString(12,datetf.getText());
          ps.setBlob(13, is);
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null, "Registered Successfully");
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }   
        
          try{  
               Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthcenter","root","");
                st = conn.createStatement();
                sql= "insert into staff_reports (ID, date, time, status) values ('"+idtf.getText()+"','"+datetf.getText()+"','"+timetf.getText()+"','New Staff Added')";
                st.executeUpdate(sql);
              

                  }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
    }
       private void showDate(){
        d = new Date();
        dd = new SimpleDateFormat("dd-MM-yyyy");
        datetf.setText(dd.format(d));
        date.setText(dd.format(d));
        
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat dd = new SimpleDateFormat("hh:mm:ss a");
                timetf.setText(dd.format(d));
            }
        }).start();
    }

       public void addUserPass(){
          
           
           try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthcenter?zeroDateTimeBehavior=convertToNull","root","");
             st = conn.createStatement();
            String sql = "insert into users (ID, Username, Password) values('" + idtf.getText() + "','" + usernametf.getText() + "','" + passwordtf.getText().toString() + "')";
            st.executeUpdate(sql);
          // JOptionPane.showMessageDialog(null, "Saved!");
          //  usernametf.setText("");
          //  passwordtf.setText("");
           // confirmtf.setText("");
        } catch (Exception c) {
            JOptionPane.showMessageDialog(this, c, "ERROR..!", JOptionPane.ERROR_MESSAGE);
        }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        timetf = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        piclabel = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        fnametf = new javax.swing.JTextField();
        mnametf = new javax.swing.JTextField();
        lnametf = new javax.swing.JTextField();
        agetf = new javax.swing.JTextField();
        mobiletf = new javax.swing.JTextField();
        bdatetf = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        usernametf = new javax.swing.JTextField();
        position = new javax.swing.JComboBox<>();
        passwordtf = new javax.swing.JPasswordField();
        confirmtf = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstf = new javax.swing.JTextArea();
        idtf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        datetf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(420, 180));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Middle Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Age:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Date of Birth:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Civil Status:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Position:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Mobile Phone:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Password:");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sign Up");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(500, 60, 97, 31);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ambuan Health Center Information System");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 20, 570, 32);

        timetf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timetf.setForeground(new java.awt.Color(255, 255, 255));
        timetf.setText("00:00:00");
        jPanel1.add(timetf);
        timetf.setBounds(980, 90, 140, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Time:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(900, 90, 47, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Date:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 90, 45, 20);

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("00-00-0000");
        jPanel1.add(date);
        date.setBounds(100, 90, 120, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Confirm Password:");

        piclabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        browse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        savebtn.setText("Register");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        fnametf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fnametf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnametfMouseClicked(evt);
            }
        });
        fnametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnametfKeyPressed(evt);
            }
        });

        mnametf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        mnametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnametfKeyPressed(evt);
            }
        });

        lnametf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lnametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnametfKeyPressed(evt);
            }
        });

        agetf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        agetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agetfKeyTyped(evt);
            }
        });

        mobiletf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        mobiletf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobiletfKeyPressed(evt);
            }
        });

        bdatetf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        status.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Single", "Married", "Widowed", "Separated" }));

        gender.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female" }));

        usernametf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        usernametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernametfKeyPressed(evt);
            }
        });

        position.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Doctor", "Nurse", "Midwife", "Dentist", "BHW" }));

        passwordtf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        passwordtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtfKeyPressed(evt);
            }
        });

        confirmtf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        confirmtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmtfKeyPressed(evt);
            }
        });

        show.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        addresstf.setColumns(20);
        addresstf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        addresstf.setRows(5);
        jScrollPane1.setViewportView(addresstf);

        idtf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtfKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Staff ID:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Date:");

        datetf.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        datetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetfActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Note: You will use this username and password when you login.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datetf, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(fnametf)
                    .addComponent(mnametf)
                    .addComponent(lnametf)
                    .addComponent(agetf)
                    .addComponent(bdatetf)
                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(position, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(browse)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(confirmtf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17)
                                            .addComponent(savebtn))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jButton1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                        .addComponent(piclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(show)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(piclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(browse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(mnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(fnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(mobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(agetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(confirmtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(datetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebtn)
                            .addComponent(jButton1))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetfActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
         //filter image extensions
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        jfc.addChoosableFileFilter(filter);
        int result = jfc.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            String Path = selectedFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, Path);
            //display image on jTable
            ImageIcon ii = new ImageIcon(Path);

            //resize image to fit jLabel
            Image image = ii.getImage().getScaledInstance(piclabel.getWidth(), piclabel.getHeight(), Image.SCALE_SMOOTH);
            piclabel.setIcon(new ImageIcon(image));
            r = Path;
        }else{
            JOptionPane.showMessageDialog(null, "No data");
        }
    }//GEN-LAST:event_browseActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    if(gender.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Select gender");
    }else if(status.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Select status");
    }else if(position.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Select position");
  
    }else{
      
       try{
           
           Class.forName("com.mysql.jdbc.Driver");
          conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthcenter","root","");
         
          String sql = "Select staff_id from staff_info WHERE staff_id="+idtf.getText();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery(); 
          
          if(rs.next()){
              JOptionPane.showMessageDialog(null, "ID Already Taken. \n Choose another one.");
          }else{
            add_data();  
          } 
       }catch(Exception e){         
       }
       
   
         if(confirmtf.getText().equals(passwordtf.getText())){
            addUserPass();
            }
        else{
            JOptionPane.showMessageDialog(this, "Password did not match", "ERROR", JOptionPane.ERROR_MESSAGE);
           }
    } 
    }//GEN-LAST:event_savebtnActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
          if (show.isSelected()) {
            passwordtf.setEchoChar((char)0);
            confirmtf.setEchoChar((char)0);
        } else {
            passwordtf.setEchoChar('*');
            confirmtf.setEchoChar('*');
        }        
    }//GEN-LAST:event_showActionPerformed

    private void usernametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametfKeyPressed
        // TODO add your handling code here:
        
             if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             if(usernametf.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Username is empty..", "Ops!", JOptionPane.ERROR_MESSAGE);
            }else{
             passwordtf.requestFocus();  
           }
        }
    }//GEN-LAST:event_usernametfKeyPressed

    private void passwordtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtfKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             if(passwordtf.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Password is empty..", "Ops!", JOptionPane.ERROR_MESSAGE);
             }else{
             confirmtf.requestFocus();
        }
       }
    }//GEN-LAST:event_passwordtfKeyPressed

    private void confirmtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmtfKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
             if(confirmtf.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Please confirm password..!", "Ops!", JOptionPane.ERROR_MESSAGE);
             }else{
             savebtn.requestFocus();
             if(confirmtf.getText().equals(passwordtf.getText())){
             addUserPass();
             }else{
             JOptionPane.showMessageDialog(this, "Please try again..", "Password did not match!", JOptionPane.ERROR_MESSAGE);
             confirmtf.requestFocus();
          }
         }
       }
    }//GEN-LAST:event_confirmtfKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnametfKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            fnametf.setEditable(true);
        }else{
            fnametf.setEditable(false);
        }
    }//GEN-LAST:event_fnametfKeyPressed

    private void mnametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnametfKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            mnametf.setEditable(true);
        }else{
            mnametf.setEditable(false);
        }
    }//GEN-LAST:event_mnametfKeyPressed

    private void lnametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnametfKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            lnametf.setEditable(true);
        }else{
            lnametf.setEditable(false);
        }
    }//GEN-LAST:event_lnametfKeyPressed

    private void mobiletfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobiletfKeyPressed
        // TODO add your handling code here:
         String phoneNumber = mobiletf.getText();
        int length = phoneNumber.length();
        char c= evt.getKeyChar();
        
        if( c>='0'&& c <= '9'){
            if(length <= 10){
                mobiletf.setEditable(true);
            }else{
                mobiletf.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==com.sun.glass.events.KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode()==com.sun.glass.events.KeyEvent.VK_DELETE){
                mobiletf.setEditable(true);
            }else{
                mobiletf.setEditable(false);
            }
        }
    }//GEN-LAST:event_mobiletfKeyPressed

    private void agetfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agetfKeyTyped
        // TODO add your handling code here:
           char input = evt.getKeyChar();
       if(!(Character.isDigit(input))
               ||(input == com.sun.glass.events.KeyEvent.VK_BACKSPACE)
               ||(input == com.sun.glass.events.KeyEvent.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_agetfKeyTyped

    private void idtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtfKeyTyped
        // TODO add your handling code here:
           char input = evt.getKeyChar();
       if(!(Character.isDigit(input))
               ||(input == com.sun.glass.events.KeyEvent.VK_BACKSPACE)
               ||(input == com.sun.glass.events.KeyEvent.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_idtfKeyTyped

    private void fnametfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnametfMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fnametfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstf;
    private javax.swing.JTextField agetf;
    private javax.swing.JTextField bdatetf;
    private javax.swing.JButton browse;
    private javax.swing.JPasswordField confirmtf;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datetf;
    private javax.swing.JTextField fnametf;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnametf;
    private javax.swing.JTextField mnametf;
    private javax.swing.JTextField mobiletf;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JLabel piclabel;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JButton savebtn;
    private javax.swing.JCheckBox show;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel timetf;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
